# Introduction to `numpy`

`NumPy` is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Library documentation: <a>http://www.numpy.org/</a>

# The base `numpy.array` object

In [1]:
import numpy as np

# declare a vector using a list as the argument
v = np.array([1., 2, 3, 4])
v

array([1., 2., 3., 4.])

In [2]:
v.shape

(4,)

In [3]:
v.ndim

1

In [4]:
v.dtype

dtype('float64')

In [5]:
w = np.array([1., 2, 3, 4], dtype='int')
w

array([1, 2, 3, 4])

In [6]:
w.dtype

dtype('int64')

In [7]:
a = np.arange(100, dtype=np.uint16)

In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=uint16)

In [9]:
-3 * a ** 2

array([     0,     -3,    -12,    -27,    -48,    -75,   -108,   -147,
         -192,   -243,   -300,   -363,   -432,   -507,   -588,   -675,
         -768,   -867,   -972,  -1083,  -1200,  -1323,  -1452,  -1587,
        -1728,  -1875,  -2028,  -2187,  -2352,  -2523,  -2700,  -2883,
        -3072,  -3267,  -3468,  -3675,  -3888,  -4107,  -4332,  -4563,
        -4800,  -5043,  -5292,  -5547,  -5808,  -6075,  -6348,  -6627,
        -6912,  -7203,  -7500,  -7803,  -8112,  -8427,  -8748,  -9075,
        -9408,  -9747, -10092, -10443, -10800, -11163, -11532, -11907,
       -12288, -12675, -13068, -13467, -13872, -14283, -14700, -15123,
       -15552, -15987, -16428, -16875, -17328, -17787, -18252, -18723,
       -19200, -19683, -20172, -20667, -21168, -21675, -22188, -22707,
       -23232, -23763, -24300, -24843, -25392, -25947, -26508, -27075,
       -27648, -28227, -28812, -29403], dtype=int32)

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=uint16)

In [11]:
b = a + 1
b

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=uint16)

In [12]:
a is b

False

In [13]:
a += 1

In [14]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=uint16)

**Warning**

Beware of the dimensions: a 1D array is not the same as a 2D array with 1 column

In [15]:
a1 = np.array([1, 2, 3])
print(a1, a1.shape, a1.ndim)

[1 2 3] (3,) 1


In [16]:
a2 = np.array([[1, 2, 3]]).T
print(a2, a2.shape, a2.ndim)

[[1]
 [2]
 [3]] (3, 1) 2


In [17]:
a2.dot(a1)

ValueError: ignored

In [ ]:
# Declare a 2D array using a nested list as the argument
M = np.array([[1,2], [3,4], [3.14, -9.17]])
M

In [ ]:
M.shape

In [ ]:
M.size

In [ ]:
M.ravel()

In [ ]:
M.ndim

In [ ]:
# arguments: start, stop, step
x = np.arange(12).reshape(4, 3)
x

In [ ]:
np.linspace(0, 10, 50)

In [ ]:
np.logspace(0, 10, 10, base=np.e, dtype=np.int32)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

# Random standard Gaussian numbers
fig = plt.figure(figsize=(10, 6))
wn = np.random.randn(1000)
bm = wn.cumsum()

plt.plot(bm, lw=3)

In [ ]:
np.diag(np.arange(10))

In [ ]:
zozo = np.zeros((10, 10))
zozo

In [ ]:
zozo.shape

In [ ]:
print(M)

In [ ]:
M[1, 1]

In [ ]:
# assign new value
M[0, 0] = 7
M[1, :] = -2
M

In [ ]:
# Warning: the next m is a **view** on M. 
# One again, no copies unless you ask for one!
m = M[0, :]
m[:] = 42
M

# Slicing

In [ ]:
# slicing works just like with anything else (lists, etc.)
A = np.array([1, 2, 3, 4, 5])
print(A)
print(A[::-1])
print(A[::2])
print(A[:-1])

In [ ]:
A = np.array([[n + m * 10 for n in range(5)] for m in range(5)])
A

In [ ]:
print(A[1:4])

In [ ]:
print(A[1:4, :])

In [ ]:
A[1]

In [ ]:
A[:, 1]

In [ ]:
A[:, ::-1]

In [ ]:
print(A)

In [ ]:
row_indices = [1, 2, 4]
print(A[row_indices])

In [ ]:
A[:, row_indices]

Another way is through masking with an array of `bool`s

In [ ]:
# index masking
B = np.arange(5)
row_mask = np.array([True, False, True, False, False])
print(B)
print(B[row_mask])

# Copies

Don't forget that `python` **does not make copies unless told to do so** (same as with any mutable type)

If you are not careful enough, this typically leads to a **lot of errors** and to being fired !!

In [ ]:
x = np.arange(6)
y = x
x[2] = 123
y

In [ ]:
x is y

In [ ]:
# A real copy
y = x.copy()

In [ ]:
# Or equivalently (but the one above is better...)
y = np.copy(x)

In [ ]:
x[0] = -12
print(x, y)

In [ ]:
x is y

To put values of x in y (copy values into an **existing** array) use

In [ ]:
y[:] = x

**Final warning**

In the next line you copy the values of `x` into an existing array `y` (of same size...)

In [ ]:
y[:] = x

While in the next line, you give another name `y` to the object with name `x`


(and actually, you should **never, never, never** write something like this)

In [ ]:
y = x

# Miscellaneous stuff

## Non-numerical values

A `numpy` array can contain other things than numeric types

In [ ]:
arr = np.array(['ou', 'la', 'la', "c'est", 'dur', 'python'])

In [ ]:
arr.sum()

In [ ]:
arr.dtype

## A matrix is no 2D array in `numpy`

We've been using only `array` or `ndarray` objects for now

The is another type: the `matrix` type

In summary: just **don't use it** (IMO) and stick with arrays

In [ ]:
# Matrix VS array objects in numpy
m1 = np.matrix(np.arange(3))
m2 = np.matrix(np.arange(3))

In [ ]:
a1 = np.arange(3)
a2 = np.arange(3)

In [ ]:
m1 * m2

In [ ]:
a1 * a2

## Sparse matrices

In [ ]:
from scipy.sparse import csc_matrix, csr_matrix, coo_matrix

probs = np.full(fill_value=1/4, shape=(4,))
X = np.random.multinomial(n=2, pvals=probs, size=4)
X

In [ ]:
X_coo = coo_matrix(X)
print(X_coo)
X_coo

In [ ]:
X_coo.nnz

In [ ]:
print(X, end='\n----\n')
print(X_coo.data, end='\n----\n')
print(X_coo.row, end='\n----\n')
print(X_coo.col, end='\n----\n')

There is also

- `csr_matrix`: sparse rows format 
- `csc_matrix`: sparse columns format

Sparse rows is often used for machine learning: sparse features vectors

But sparse column format useful as well (e.g. coordinate gradient descent)

## Bored of seing too many decimals?

In [ ]:
X = np.random.randn(5, 5)
X

In [ ]:
# All number displayed by numpy (in the current kernel) are with 3 decimals max
np.set_printoptions(precision=3)
print(X)
np.set_printoptions(precision=8)

## Not limited to 2D!

`numpy` arrays can have any number of dimension (hence the name `ndarray`)

In [ ]:
X = np.arange(18).reshape(3, 2, 3)
X

In [ ]:
X.shape

In [ ]:
X.ndim

# Aggregations and statistics

In [ ]:
A = np.arange(42).reshape(7, 6)
A

In [ ]:
A.sum()

In [ ]:
A[:, 3].mean()

In [ ]:
A.mean(axis=0)

In [ ]:
A.mean(axis=1)

In [ ]:
A[:,3].std(), A[:,3].var()

In [ ]:
A[:,3].min(), A[:,3].max()

In [ ]:
A.cumsum(axis=1)

In [ ]:
# sum of diagonal
A.trace()

# Linear Algebra

In [ ]:
A = np.arange(30).reshape(6, 5)
v1 = np.arange(0, 5)
v2 = np.arange(5, 10)

In [ ]:
v1

In [ ]:
v2

In [ ]:
v1 * v2

## Inner products

In [ ]:
# Inner product between vectors
print(v1.dot(v2))

# You can use also (but first solution is better)
print(np.dot(v1, v2))

In [ ]:
A, v1

In [ ]:
A.shape, v1.shape

In [ ]:
# Matrix-vector inner product
A.dot(v1)

In [ ]:
# Transpose
A.T

In [ ]:
print(v1)
# Inline operations (same for *=, /=, -=)
v1 += 2

## Linear systems

In [ ]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([1,2,3])
print(A, b, sep=2 * '\n')

In [ ]:
# solve a system of linear equations
x = np.linalg.solve(A, b)
x

In [ ]:
A.dot(x)

## Eigenvalues and eigenvectors

In [ ]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)

evals, evecs = np.linalg.eig(A)
evals

In [ ]:
evecs

### Singular value decomposition (SVD)

Decomposes any matrix $A \in \mathbb R^{m \times n}$ as follows:
$$
A = U S V^\top
$$
where 
- $U$ and $V$ are orthonormal matrices (meaning that $U^\top U = I$ and $V^\top V = I$)
- $S$ is a diagonal matrix that contains the singular values in decreasing order

In [ ]:
print(A)
U, S, V = np.linalg.svd(A)

In [ ]:
U.dot(np.diag(S)).dot(V)

In [ ]:
# U and V are indeed orthonormal
np.set_printoptions(precision=2)
print(U.T.dot(U), V.T.dot(V), sep=2 * '\n')
np.set_printoptions(precision=8)

## Exercice: the racoon SVD

- Load the racoon face picture using `scipy.misc.face()`
- Visualize the picture
- Write a function which reshapes the picture into a 2D array, and computes the best rank-r approximation of it (the prototype of the function is `compute_approx(X, r)`
- Display the different approximations for r between 5 and 100

In [ ]:
import numpy as np
from scipy.misc import face
import matplotlib.pyplot as plt
%matplotlib inline

X = face()
plt.imshow(X)
_ = plt.axis('off')

In [ ]:
def compute_approx(X: np.ndarray, r: int):
    """Computes the best rank-r approximation of X using SVD.
    We expect X to the 3D array corresponding to a color image, that we 
    reduce to a 2D one to apply SVD (no broadcasting).
    
    Parameters
    ----------
    X : `np.ndarray`, shape=(n_rows, n_cols, 3)
        The input 3D ndarray
    
    r : `int`
        The desired rank
        
    Return
    ------
    output : `np.ndarray`, shape=(n_rows, n_cols, 3)
        The best rank-r approximation of X
    """
    n_rows, n_cols, n_channels = X.shape
    # Reshape X to a 2D array
    X_reshape = X.reshape(n_rows, n_cols * n_channels)
    # Compute SVD
    U, S, V = np.linalg.svd(X_reshape, full_matrices=False)
    # Keep only the top r first singular values
    S[r:] = 0
    # Compute the approximation
    X_reshape_r = U.dot(np.diag(S)).dot(V)
    # Put it between 0 and 255 again and cast to integer type
    return X_reshape_r.clip(min=0, max=255).astype('int')\
        .reshape(n_rows, n_cols, n_channels)

In [ ]:
ranks = [100, 70, 50, 30, 10, 5]
n_ranks = len(ranks)
for i, r in enumerate(ranks):
    X_r = compute_approx(X, r)
    # plt.subplot(n_ranks, 1, i + 1)
    plt.figure(figsize=(5, 5))
    plt.imshow(X_r)
    _ = plt.axis('off')
    plt.title('Rank %d approximation of the racoon' % r, fontsize=16)
    plt.tight_layout()