# Python

Η [Python](https://www.python.org/) είναι μια δυναμική γλώσσα προγραμματισμού, με αυτόματη διαχείριση μνήμης που υποστηρίζει αντικειμενοστραφή, συναρτησιακό και διαδικαστικό προγραμματισμό.

Υποστηρίζονται παράλληλα 2 εκδόσεις της python: η **2.7** και η **3.6**. Εμείς στα πλαίσια του εργαστηρίου θα χρησιμοποιήσουμε την 3.6.

## Διαφορές Python 2 me 3

Δεν υπάρχουν μεγάλλες διαφορές ανάμεσα στις python 2 και 3. Η κυριότερες από αυτές που συναντάμε είναι η εντολή `print` και ο τελεστής της διαίρεσης `/`:

```
# python 2:
print 'hi'
# python 3:
print('hi')

# python 2:
5/2 # κάνει 2
# python 3:
5/2 # κάνει 2.5
```

Η python 3 είχε αργή υιοθέτηση από τις ήδη υπάρχουσες βιβλιοθήκες της python, ενώ οι περισσότερες από αυτές εξακολουθούν να υποστίηρζουν python 2. Έχουν υπάρξει και προσπάθειες ενοποίησης της συμπεριφοράς των 2 γλωσσών ([\_\_future\_\_](https://docs.python.org/2/library/__future__.html), [six](https://pythonhosted.org/six/) modules) ώστε ο ίδιος κώδικας να τρέχει και σε python2 και σε python3.

Πιο αναλυτικά οι διαφορές των 2 εκδόσεων υπάρχουν [εδώ](http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html).

## Package Management

Το βασικό αποθετήριο πακέτων για την python είναι το [PyPI](https://pypi.python.org/pypi), ενώ η εγκατάστασή τους γίνεται μέσω του [pip](https://pip.pypa.io/en/stable/).

Για την εγκατάσταση του pip κατεβάζουμε το [get-pip.py](https://bootstrap.pypa.io/get-pip.py) και το τρέχουμε με την παρακάτω εντολή:

```
python get-pip.py
```

Τώρα μπορούμε να εγκαθιστούμε πια πακέτα μέσω του pip. Πχ για την εγκατάσταση του πακέτου *numpy* αρκεί να γράψουμε την παρακάτω εντολή:

```
pip install numpy
```

## Λίγα λόγια για τη δομή του προγράμματος

Προκειμένου να κρατήσει πιο απλή και ευανάγνωστη σύνταξη, η python **δεν** υποστηρίζει ερωτηματικά `(;)` και μπλόκ κώδικα σε αγκύλες `{...}` όπως μπορεί να έχουμε δει σε άλλες γλώσσες. Αντίθετα θεωρεί ότι κάθε γραμμή είναι (συνήθως) μια εντολή και **επιβάλλει** τη σωστή στοίχιση του προγράμματος.

Για στοίχιση μπορούμε να χρησιμοποιήσουμε είτε tab είτε κενά αλλά όχι και τα δύο! [Spaces or Tabs](https://legacy.python.org/dev/peps/pep-0008/#tabs-or-spaces)

Όταν αποθηκεύουμε τιμές μέσα σε μεταβλητές δεν χρειάζεται να δηλώσουμε τον τύπο τους, ενώ αυτός επιτρέπεται να αλλάζει στη διάρκεια του προγράμματος.

Σχόλια βάζουμε στον κώδικα με την δίεση `#`.


## Hello World!

Για να τυπώσουμε κάτι στην python χρησιμοποιούμε την εντολή `print`: 

In [17]:
print('Hello world!')

Hello world!


## Τύποι δεδομένων

Οι βασικότεροι τύποι δεδομένων που βρίσκονται στη βασική έκδοση της python είναι οι εξής:

- Αριθμητικά δεδομένα: `int`, `float`, `long`, `complex`, κτλ.
- Ακολουθιακά δεδομένα: `string`, `list`, `tuple`, κτλ.
- Λοιπά: `dict`, `set`, κτλ.

### Αριθμητικά δεδομένα

Στην Python δεν χρειάζεται να ορίζουμε τον τύπο της μεταβλητής μαζί με το όνομά της.

In [18]:
a = 5 # integer
b = 2.2 # float

print('a + b =', a + b, 'vvrr')
print('a - b =', a - b)
print('a / b =', a / b)
print('a * b =', a * b)
print('a ** b =', a ** b) # δύναμη

a + b = 7.2 vvrr
a - b = 2.8
a / b = 2.2727272727272725
a * b = 11.0
a ** b = 34.493241536530384


Για πιο σύνθετες πράξεις πρέπει να χρησιμοποιήσουμε κάποια εξωτερική βιβλιοθήκη.

In [19]:
import math # ορίζουμε ποιο πακέτο θα χρησιμοποιήσουμε

print('exp(a) =', math.exp(a)) # τρέχουμε τις αντίστοιχες συναρτήσεις
print ('cos(b) =', math.cos(b))

exp(a) = 148.4131591025766
cos(b) = -0.5885011172553458


### Strings

Στην python μπορούμε να ορίσουμε stings είτε μέσα σε μονά ('...') είτε σε διπλά ("...") εισαγωγικά. 

In [20]:
s = 'my String'

print ('lowercase:', s.lower())
print ('uppercase:', s.upper())
print ('replace y-->e:', s.replace('y', 'e'))
print ('a={}, b={}, s={}'.format(a, b, s)) # χρήση του format για να εισάγουμε μεταβλητές μέσα στο sting

lowercase: my string
uppercase: MY STRING
replace y-->e: me String
a=5, b=2.2, s=my String


### Lists & tuples

Οι λίστες είναι ο πιο "ευέλικτος" τύπος δεδομένων στην Python. Μια λίστα μπορεί να περιέχει ότι τύπο δεδομένων θέλουμε, ακόμα και άλλες λίστες! Δεν χρειάζεται να ορίσουμε το μέγεθος της λίστας εκ των προτέρων, ενώ αυτό μπορεί να αλλάξει πιο μετά στον κώδικά μας. Οι λίστες στην python ορίζονται μέσα σε αγκύλες [].

In [21]:
l = [1, 2, 3, 'abc', a, b, s]
print ('original list:', l)
print ('4th element:', l[3]) # αναφορά στο 4ο στοιχείο της λίστας (η αρίθμηση ξεκινάει από το 0)
print ('first 3 elemetns:', l[:3])
print ('last 2 elements:', l[-2:])
print ('pop:', l.pop()) # αφαιρεί το τελευταίο στοιχείο της λίστας και το επιστρέφει σαν αποτέλεσμα
l.append('new element') # τοποθετεί ένα νέο στοιχείο στο τέλος της λίστας
del l[3] # διαγράφει το 4ο στοιχείο της λίστας
print ('new list:', l)

original list: [1, 2, 3, 'abc', 5, 2.2, 'my String']
4th element: abc
first 3 elemetns: [1, 2, 3]
last 2 elements: [2.2, 'my String']
pop: my String
new list: [1, 2, 3, 5, 2.2, 'new element']


Ένας ειδικός τύπος λίστας είναι το `range` το οποίο επιστρέφει μια **λίστα από ακεραίους**. 

- Αν βάλουμε ένα όρισμα: επιστρέφει μια λίστα ακεραίων από το 0 μέχρι και τον προηγούμενο του αριθμού αυτού.
- Αν βάλουμε δυο ορίσματα: επιστρέφει μια λίστα ακεραίων από τον πρώτο μέχρι τον προηγούμενο του δεύτερου αριθμού.
- Αν βάλουμε τρία ορίσματα: επιστρέφει μια λίστα ακεραίων από τον πρώτο μέχρι τον προηγούμενο του δεύτερου αριθμού με βήμα ίσο με τον τρίτο αριθμό.

In [22]:
print (range(5)) # λίστα ακεραίων από το 0 μέχρι το 4
print (range(3,9)) # λίστα ακεραίων από το 3 μέχρι το 8
print (range(5,15,2)) # λίστα περιττών ακεραίων από το 5 μέχρι το 14

range(0, 5)
range(3, 9)
range(5, 15, 2)


Τα tuples είναι δομές δεδομένων παρόμοιες με τις λίστες μόνο που **δεν μπορούν να αλλάξουν** κατά τη διάρκεια του προγράμματος. Τα tuples ορίζονται μέσα σε παρενθέσεις ().

In [23]:
t = (1,2,3) # immutable object
del t[1]

TypeError: ignored

### Dictionaries

Τα dictionaries **δεν έχουν αρίθμηση** όπως είδαμε πρίν με τις λίστες και τα tuples. Λειτουργούν με τη λογική των κλειδιών (**keys**) και των τιμών (**values**). Τα dictionaries ορίζονται μέσα σε άγκυστρα {}.

In [25]:
d = {'name':'John', 'age': 26}
print ('original dictionary:', d)
print ('d[name]: ', d['name'])
d['address'] = 'Downtown' # πρoσθήκη νέου στοιχείου
del d['age'] # διαγραφή στοιχείου
print ('new dictionary:', d)
print ('dictionary keys:', d.keys()) # επιστρέφει όλα τα κλειδιά
print ('dictionary values:', d.values()) # επιστρέφει όλες τις τιμές

original dictionary: {'name': 'John', 'age': 26}
d[name]:  John
new dictionary: {'name': 'John', 'address': 'Downtown'}
dictionary keys: dict_keys(['name', 'address'])
dictionary values: dict_values(['John', 'Downtown'])


## Έλεγχος ροής

Προσοχή θέλει η στοίχιση καθώς καθορίζει τα μπλοκ των `if`, `for` και `while`.

### Εντολή if

In [26]:
x = 5

if x > 6:
    print ('x is greater than 6')
elif x < 6 and x > 4:
    print ('x is smaller than 6 and greater than 4')
else:
    print ('x is smaller than 4')

x is smaller than 6 and greater than 4


### Εντολή while

In [27]:
x = 0

while x < 5:
    print (x)
    x += 1

0
1
2
3
4


### Εντολή for

In [28]:
for i in l: # διατρέχει τη λίστα l 
    print (i) # και τυπώνει τα στοιχεία της

print

for i in range(3, 11, 2): # το range δημιουργεί μια λίστα ακεραίων από το 3 μέχρι το 11 με βήμα 2
    print (i)

1
2
3
5
2.2
new element
3
5
7
9


Η python υποστηρίζει και τις εντολές break, continue και pass, για ακόμα μεγαλύτερο έλεγχο στην επανάληψη.

Όπως είπαμε και προηγουμένως έχει μεγάλη σημασία η στοίχιση των εντολών!

In [29]:
for i in range(5):
    if i < 2:
        print ('{} is smaller than 2'.format(i))
    elif i == 2:
        print ('{} is equal to 2'.format(i))
    else:
        print ('{} is greater than 2'.format(i))

0 is smaller than 2
1 is smaller than 2
2 is equal to 2
3 is greater than 2
4 is greater than 2


### List comprehension

Μια πολύ βολική σύνταξη της python για τον ορισμό λιστών.

Πχ θέλουμε να φτιάξουμε μια λίστα (`squares`) που να περιέχει τα τετράγωνα των αριθμών από το 0 μέχρι το 9. Με όσα έχουμε μάθει μέχρι στιγμίς αυτό θα το γράφαμε ως εξής:

In [30]:
squares = []
for i in range(10):
    squares.append(i**2)
print (squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Κάνοντας χρήση του list comprehension το παραπάνω γράφεται πιο απλά ως εξής

In [31]:
squares = [x ** 2 for x in range(10)]
print (squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Το list comprehension μπορεί να γίνει πιο σύνθετο βάζοντας παραπάνω από μια `for` και `if` μέσα. Η παρακάτω εντολή πάιρνει ένα string (`'hello world!'`) και κάνει τα φωνίεντά του κεφαλαία.

In [32]:
print (''.join([x.upper() if x in 'aeioyu' else x for x in 'hello world!']))

hEllO wOrld!


## Συναρτήσεις

Οι συναρτήσεις της python δέχονται [δύο τύπους ορισμάτων](https://docs.python.org/2/glossary.html#term-argument) τα **keyword (optional) arguments** και τα **positional arguments**. Τα πρώτα είναι προεραιτικά (αν δεν τα ορίσει ο χρήστης παίρνουν μια default τιμή), έχουν όνομα και μπορεί να τα τοποθετήσουμε με όποια σειρά θέλουμε κατά την κλήση της συνάρτησης. Τα δεύτερα είναι υποχρεωτικά και πρέπει να μπουν με τη σειρά. 

### Positional Arguments

In [33]:
def my_func(a, b):
    return a * (a + b)

print(my_func(3,4))

21


### Keyword Arguments

In [34]:
def my_func2(a=0, b=0):
    return a * (a + b)

print (my_func2(3,4)) # δέχεται a=3, b=4
print (my_func2()) # δέχεται τις default τιμές: a=0, b=0
print (my_func2(3)) # δέχεται a=3, b=0
print (my_func2(a=3)) # δέχεται a=3, b=0
print (my_func2(b=3)) # δέχεται b=3, a=0
print (my_func2(b=3, a=4))  # δέχεται a=4, b=3

21
0
9
9
0
28


## Άσκηση 1:

Φτιάξτε μια συνάρτηση που να δέχεται μια παράμετρο Ν και να επιστρέφει τους πρώτους αριθμούς μέχρι το Ν σε μορφή λίστας.

## Αρχεία

Για να γράψουμε σε να αρχείο χρησιμοποιούμε την συνάρτση `open()` της python. Δέχεται 2 ορίσματα:

- Το όνομα του αρχείου που θα ανοίξει/δημιουργήσει (ή το path του)
- Το mode στο οποίο θα το ανοίξει (πχ για εγγραφή, για ανάγνωση)

In [0]:
f = open('doc.txt', 'w') # ανοίγουμε ένα αρχείο σε mode 'w' --> write
f.write('my first line\n') # γράφουμε μια γραμμή στο αρχείο
f.close() # κλείνουμε το αρχείο

Η παραπάνω εντολή δημιούργησε ένα αρχείο στον φάκελο από τον οποίο τρέχουμε το notebook. Αν θέλαμε άλλη τοποθεσία θα έπρεπε να βάλουμε το path του αρχείου μαζί με το όνομά του (πχ σε linux `'/home/thanos/Desktop/doc.txt'`)
Πρέπει να δίνουμε προσοχή να κλείνουμε το αρχείο! Για να μην το ξεχνάμε προτιμάμε να χρησιμοποιούμε την παρακάτω σύνταξη:

In [0]:
with open('doc.txt', 'a') as f: # ανοίγουμε σε mode 'a' --> append
    f.write('my second line\n')

Ανάγνωση κειμένου.

In [37]:
with open('doc.txt', 'r') as f: # ανοίγουμε σε mode 'r' --> read
    doc = []
    for line in f: # διατρέχουμε το κείμενο γραμμή-γραμμή
        doc.append(line) # αποθηκεύουμε κάθε γραμμή ξεχωριστά σε μια λίστα
        
print(doc)

['my first line\n', 'my second line\n']


## Πίνακες

Η python από μόνη της δεν υποστηρίζει πράξεις πινάκων. Για το λόγο αυτό χρησιμοποιούμε τη βιβλιοθήκη [numpy](http://www.numpy.org/). Προσοχή μην μπλέκουμε τύπους δεδομένων σε πίνακες (δηλ. **κάθε πίνακας να έχει δεδομένα του ίδιου τύπου**, π.χ. float32)

In [38]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[11,22,33],[44,55,66],[77,88,99]])

print (a)
print (b)
print ('a + b =\n', a + b) 
print ('elementwise: a * b =\n', a * b) # elementwise
print ('matrix multiplication: a * b =\n', np.dot(a, b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
a + b =
 [[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]]
elementwise: a * b =
 [[ 11  44  99]
 [176 275 396]
 [539 704 891]]
matrix multiplication: a * b =
 [[ 330  396  462]
 [ 726  891 1056]
 [1122 1386 1650]]


Η numpy υποστηρίζει και πράξεις ανάμεσα σε πίνακες με ασύμβατες διαστάσεις μέσω του [broadcasting](http://www.astroml.org/_images/fig_broadcast_visual_1.png).

In [39]:
c = np.array([0.5, 1, 1.5])
print ('a + c =\n', a + c) # επαναλαμβάνει τον πίνακα c 3 φορές ώστε να ταιριάξει με τις διαστάσεις του a πριν κάνει την πράξη
print ('a + 1 =\n', a + 1) # elementwise

a + c =
 [[ 1.5  3.   4.5]
 [ 4.5  6.   7.5]
 [ 7.5  9.  10.5]]
a + 1 =
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Στατιστικά στοιχεία πίνακα

In [40]:
print ('τύπος δεδομένων:', a.dtype)
print ('διαστάσεις:', a.shape)
print ('άθροισμα στοιχείων πίνακα:', a.sum())
print ('άθροισμα στοιχείων ανά γραμμή:\n', a.sum(axis=1)) # ανά στήλη θα ήταν axis=0
print ('μέγιστη τιμή πίνακα:', a.max())
print ('μέγιστo στοιχείο ανά στήλη:\n', a.max(axis=0))

τύπος δεδομένων: int64
διαστάσεις: (3, 3)
άθροισμα στοιχείων πίνακα: 45
άθροισμα στοιχείων ανά γραμμή:
 [ 6 15 24]
μέγιστη τιμή πίνακα: 9
μέγιστo στοιχείο ανά στήλη:
 [7 8 9]


### Δημιουργία πινάκων

In [41]:
z = np.zeros((2,2)) # φτιάχνει έναν πίνακα με μηδενικά σχήματος 2x2
print (z)
d = np.arange(1,10) # φτιάχνει έναν πίνακα με τιμές από το 1 μέχρι το 9
print (d)

[[0. 0.]
 [0. 0.]]
[1 2 3 4 5 6 7 8 9]


### Indexing & slicing

In [42]:
print (d[4]) # δείχνει το 5ο στοιχείο του d
print (a[1,2]) # δείχνει το 3ο στοιχείο από τη δεύτερη γραμμή του a

print (a[:,0]) # φέρνει όλα τα στοιχεία της πρώτης στήλης του a

5
6
[1 4 7]


### Αλλαγή σχήματος πίνακα

In [43]:
print ('old shape:', d.shape)
d = d.reshape((3,3)) # αλλάζουμε το σχήμα σε 3x3
print ('new shape:', d.shape)
print (d)

old shape: (9,)
new shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Επίσης υποστηρίζονται και λογικές πράξεις μεταξύ πινάκων.

In [44]:
d = np.arange(9,0,-1).reshape((3,3))
print ('a =\n', a)
print ('d =\n', d)

print ('a > d =\n', a > d)

a =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
d =
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
a > d =
 [[False False False]
 [False False  True]
 [ True  True  True]]


## Άσκηση 2:

Φτιάξτε μια συνάρτηση που να δέχεται 2 πίνακες Α, Β, να ελέγχει αν αυτοί έχουν τις ίδιες διαστάσεις και να εκτελεί την πράξη Α - Β.

## Κλάσεις και αντικείμενα

In [0]:
class Rectangle:
    
    def __init__(self, h, w):
        # constructor
        
        self.height = h # δεν υπάρχουν private μεταβλητές στην python
        self.width = w
        
    def area(self):
        return self.height * self.width
    
    def perimeter(self):
        return 2 * (self.height + self.width)
    
    def diagonal(self):
        return math.sqrt(self.height ** 2 + self.width ** 2)

In [46]:
rec1 = Rectangle(4,2)
rec2 = Rectangle(3,3)

print ('Equal areas?', rec1.area() == rec2.area())
print ('Equal perimeters?', rec1.perimeter() == rec2.perimeter())
print ('Equal diagonals?', rec1.diagonal() == rec2.diagonal())

Equal areas? False
Equal perimeters? True
Equal diagonals? False


## Άσκηση 3:

Φτιάξτε μια κλάση με όνομα Circle η οποία θα έχει 2 μεθόδους που θα υπολογίζουν την περιφέρεια και το εμβαδόν του. Χρησιμοποιήστε την σταθερά math.pi

## Χειρισμός αρχείων csv

Ένα πολύ χρήσιμο format αρχείων είναι το **csv** (comma separated values), το οποίο μας επιτρέπει εύκολα να αποθηκεύουμε και να διαβάζουμε πίνακες.

In [47]:
print (a)
np.savetxt('myarray.csv', a, delimiter=',') # αποθηκεύουμε σε ένα αρχείο τον πίνακά μας
                                            # τα κελιά χωρίζονται με , και οι γραμμές με \n

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Για να το φορτώσουμε το αρχείο:

In [48]:
loaded_arr = np.loadtxt('myarray.csv', delimiter=',')
print (loaded_arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Pandas

Η [pandas](http://pandas.pydata.org/) είναι μια βιβλιοθήκη της python που περιέχει καινούργια data structures (όπως το [series](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.html) και το [dataframe](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)) καθώς και εργαλεία ανάλυσης δεδομένων. Εμείς θα την χρησιμοποιήσουμε κυρίως για το input-output. Η βασική δομή που θα χρησιμοποιήσουμε είναι το **dataframe** το οποίο είναι ένας πίνακας που, σε αντίθεση με το numpy, μπορεί και δέχεται διαφορετικούς  τύπους δεδομένων ανά στήλη.

In [49]:
import pandas as pd
df = pd.DataFrame({'A' : range(5,10),
                   'B' : 'blabla',
                   'C' : np.arange(0,5)[::-1],
                   'D' : 1})
print (df)

   A       B  C  D
0  5  blabla  4  1
1  6  blabla  3  1
2  7  blabla  2  1
3  8  blabla  1  1
4  9  blabla  0  1


Για να δούμε τους τύπους δεδομένων του dataframe:

In [50]:
print (df.dtypes)

A     int64
B    object
C     int64
D     int64
dtype: object


Οι στήλες του dataframe έχουν ονόματα με τα οποία μπορούμε να αναφερθούμε σε αυτές (σαν ένα dictionary). Για να δούμε τα ονόματα αυτά μπορούμε να πατήσουμε την εντολή df.columns. Αντίστοιχα υπάρχει και η df.index για τα index των γραμμών. Για να απομονώσουμε τα στοιχεία της δεύτερης στήλης (που έχουμε ονομάσει *B*):

In [51]:
print (df['B'])

0    blabla
1    blabla
2    blabla
3    blabla
4    blabla
Name: B, dtype: object


Στις γραμμές το slicing γίνεται όπως και στο numpy.

In [52]:
df[1:3]

A       B  C  D
1  6  blabla  3  1
2  7  blabla  2  1

Προσοχή θέλει όταν θέλουμε να πάρουμε μια μοναδική γραμμή. Δεν δουλεύει το indexing όπως στην numpy:

In [53]:
df[3]

KeyError: ignored

Αντίθετα πρέπει να χρησιμοποιήσουμε το `.loc` ή το `.iloc`.

In [54]:
print(df.loc[3])

A         8
B    blabla
C         1
D         1
Name: 3, dtype: object


Βασικά στατιστικά στοιχεία πίνακα:

In [55]:
df.describe() # δουλεύει για τις στήλες που περιέχουν αριθμητικά δεδομένα

A         C    D
count  5.000000  5.000000  5.0
mean   7.000000  2.000000  1.0
std    1.581139  1.581139  0.0
min    5.000000  0.000000  1.0
25%    6.000000  1.000000  1.0
50%    7.000000  2.000000  1.0
75%    8.000000  3.000000  1.0
max    9.000000  4.000000  1.0

Μια ενδιαφέρουσα εφαρμογή στο pandas είναι η εφαρμογή φίλτρων στο dataframe. Π.χ. αν θέλουμε να πάρουμε τις γραμμές στις οποίες η στήλη *C* έχει τιμή μικρότερη από 3:

In [56]:
df[df['C'] < 3 ]

A       B  C  D
2  7  blabla  2  1
3  8  blabla  1  1
4  9  blabla  0  1

Το pandas παρέχει και τις δικές του συναρτήσεις για εγγραφή και ανάγνωση απο csv (`to_csv()` και `read_csv()` αντίστοιχα). Προσοχή θέλει το δεύτερο γιατί το pandas θεωρεί ότι από default η πρώτη γραμμή είναι τα ονόματα των στηλών. Αν το csv μας έχει (όπως στην προηγούμενη περίπτωση με το numpy) μόνο τιμές, πρέπει να ορίσουμε `header=None` ως επιπλέον παράμετρο της συνάρτησης. 

# Βιβλιογραφία

Προτεινόμενο βιβλίο

Python Cookbook (Third edition) - David Beazley and Brian K. Jones

![alt text](https://covers.oreillystatic.com/images/0636920027072/lrg.jpg)

[Άλλες επιλογές](https://data-flair.training/blogs/best-python-book/)
